[tool.poetry]
name = "skyshop"
version = "0.1.0"
description = ""
authors = ["JennaFi <fi@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

